blueprint:
  domain: automation
  name: Philips Hue Tap Dial Switch
  description: Philips Hue Tap Dial Switch (RDM002) configuration using ZHA

  input:
    zha_device:
      name: Philips Hue Tap Dial Switch
      description: List of available Philips Hue Tap Dial Switches
      selector:
        device:
          integration: zha
          model: RDM002
          multiple: false

    Button_1_1x_Press:
      name: Button 1 Single 1 (1x) Press
      description: Button 1 was pressed 1 time
      default: []
      selector:
        action: {}
    Button_1_2x_Press:
      name: Button 1 Double (2x) Press
      description: Button 1 was pressed 2 times
      default: []
      selector:
        action: {}
    Button_1_3x_Press:
      name: Button 1 Triple (3x) Press
      description: Button 1 was pressed 3 times
      default: []
      selector:
        action: {}
    Button_1_4x_Press:
      name: Button 1 Quadruple  (4x) Press
      description: Button 1 was pressed 4 times
      default: []
      selector:
        action: {}
    Button_1_5x_Press:
      name: Button 1 Quintuple (5x) Press
      description: Button 1 was pressed 5 times
      default: []
      selector:
        action: {}
    Button_1_Long_Press:
      name: Button 1 Long Press
      description: Button 1 was pressed for a longer time
      default: []
      selector:
        action: {}
    Button_1_Long_Release:
      name: Button 1 Long Release
      description: Button 1 was released after a longer press
      default: []
      selector:
        action: {}
    Button_1_Short_Release:
      name: Button 1 Short Release
      description: Button 1 was released after a shorter press
      default: []
      selector:
        action: {}

    Button_2_1x_Press:
      name: Button 2 Single 1 (1x) Press
      description: Button 2 was pressed 1 time
      default: []
      selector:
        action: {}
    Button_2_2x_Press:
      name: Button 2 Double (2x) Press
      description: Button 2 was pressed 2 times
      default: []
      selector:
        action: {}
    Button_2_3x_Press:
      name: Button 2 Triple (3x) Press
      description: Button 2 was pressed 3 times
      default: []
      selector:
        action: {}
    Button_2_4x_Press:
      name: Button 2 Quadruple  (4x) Press
      description: Button 2 was pressed 4 times
      default: []
      selector:
        action: {}
    Button_2_5x_Press:
      name: Button 2 Quintuple (5x) Press
      description: Button 2 was pressed 5 times
      default: []
      selector:
        action: {}
    Button_2_Long_Press:
      name: Button 2 Long Press
      description: Button 2 was pressed for a longer time
      default: []
      selector:
        action: {}
    Button_2_Long_Release:
      name: Button 2 Long Release
      description: Button 2 was released after a longer press
      default: []
      selector:
        action: {}
    Button_2_Short_Release:
      name: Button 2 Short Release
      description: Button 2 was released after a shorter press
      default: []
      selector:
        action: {}

    Button_3_1x_Press:
      name: Button 3 Single 1 (1x) Press
      description: Button 3 was pressed 1 time
      default: []
      selector:
        action: {}
    Button_3_2x_Press:
      name: Button 3 Double (2x) Press
      description: Button 3 was pressed 2 times
      default: []
      selector:
        action: {}
    Button_3_3x_Press:
      name: Button 3 Triple (3x) Press
      description: Button 3 was pressed 3 times
      default: []
      selector:
        action: {}
    Button_3_4x_Press:
      name: Button 3 Quadruple  (4x) Press
      description: Button 3 was pressed 4 times
      default: []
      selector:
        action: {}
    Button_3_5x_Press:
      name: Button 3 Quintuple (5x) Press
      description: Button 3 was pressed 5 times
      default: []
      selector:
        action: {}
    Button_3_Long_Press:
      name: Button 3 Long Press
      description: Button 3 was pressed for a longer time
      default: []
      selector:
        action: {}
    Button_3_Long_Release:
      name: Button 3 Long Release
      description: Button 3 was released after a longer press
      default: []
      selector:
        action: {}
    Button_3_Short_Release:
      name: Button 3 Short Release
      description: Button 3 was released after a shorter press
      default: []
      selector:
        action: {}

    Button_4_1x_Press:
      name: Button 4 Single 1 (1x) Press
      description: Button 4 was pressed 1 time
      default: []
      selector:
        action: {}
    Button_4_2x_Press:
      name: Button 4 Double (2x) Press
      description: Button 4 was pressed 2 times
      default: []
      selector:
        action: {}
    Button_4_3x_Press:
      name: Button 4 Triple (3x) Press
      description: Button 4 was pressed 3 times
      default: []
      selector:
        action: {}
    Button_4_4x_Press:
      name: Button 4 Quadruple  (4x) Press
      description: Button 4 was pressed 4 times
      default: []
      selector:
        action: {}
    Button_4_5x_Press:
      name: Button 4 Quintuple (5x) Press
      description: Button 4 was pressed 5 times
      default: []
      selector:
        action: {}
    Button_4_Long_Press:
      name: Button 4 Long Press
      description: Button 4 was pressed for a longer time
      default: []
      selector:
        action: {}
    Button_4_Long_Release:
      name: Button 4 Long Release
      description: Button 4 was released after a longer press
      default: []
      selector:
        action: {}
    Button_4_Short_Release:
      name: Button 4 Short Release
      description: Button 4 was released after a shorter press
      default: []
      selector:
        action: {}

    Rotary_Clockwise:
      name: Clockwise Rotation
      description: |
        Rotary dial rotated in the clockwise orientation
        You can use the {{ step_size }} variable to get the step_size
        Fun for dynamically changing the light brightness based on the dial speed
      default: []
      selector:
        action: {}
    Rotary_Counterclockwise:
      name: Counter Clockwise Rotation
      description: |
        Rotary dial rotated in the counter clockwise orientation
        You can use the {{ step_size }} variable to get the step_size
        Fun for dynamically changing the light brightness based on the dial speed
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent
variables:
  device_id: !input zha_device

trigger:
  - platform: event
    event_type: zha_event
condition: "{{ trigger.event.data.device_id == device_id }}"

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      step_mode: "{{ trigger.event.data.params.step_mode }}"
      step_size: "{{ trigger.event.data.params.step_size }}"
      button: "{{ trigger.event.data.params.button }}"

  - service: logbook.log
    data:
      name: Button
      message: "{{ button }}"
  - service: logbook.log
    data:
      name: Step mode
      message: "{{ step_mode }}"
  - service: logbook.log
    data:
      name: Device
      message: "{{ zha_device }}"
  - service: logbook.log
    data:
      name: Command
      message: "{{ command }}"

  - choose:
      # Button 1
      - conditions: '{{ command == "button_1_press" }}'
        sequence: !input Button_1_1x_Press
      - conditions: '{{ command == "button_1_double_press" }}'
        sequence: !input Button_1_2x_Press
      - conditions: '{{ command == "button_1_triple_press" }}'
        sequence: !input Button_1_3x_Press
      - conditions: '{{ command == "button_1_quadruple_press" }}'
        sequence: !input Button_1_4x_Press
      - conditions: '{{ command == "button_1_quintuple_press" }}'
        sequence: !input Button_1_5x_Press
      - conditions: '{{ command == "button_1_hold" }}'
        sequence: !input Button_1_Long_Press
      - conditions: '{{ command == "button_1_short_release" }}'
        sequence: !input Button_1_Long_Release
      - conditions: '{{ command == "button_1_long_release" }}'
        sequence: !input Button_1_Short_Release

      # Button 2
      - conditions: '{{ command == "button_2_press" }}'
        sequence: !input Button_2_1x_Press
      - conditions: '{{ command == "button_2_double_press" }}'
        sequence: !input Button_2_2x_Press
      - conditions: '{{ command == "button_2_triple_press" }}'
        sequence: !input Button_2_3x_Press
      - conditions: '{{ command == "button_2_quadruple_press" }}'
        sequence: !input Button_2_2x_Press
      - conditions: '{{ command == "button_2_quintuple_press" }}'
        sequence: !input Button_2_5x_Press
      - conditions: '{{ command == "button_2_hold"}}'
        sequence: !input Button_2_Long_Press
      - conditions: '{{ command == "button_2_short_release" }}'
        sequence: !input Button_2_Long_Release
      - conditions: '{{ command == "button_2_long_release" }}'
        sequence: !input Button_2_Short_Release

      # Button 3
      - conditions: '{{ command == "button_3_press" }}'
        sequence: !input Button_3_1x_Press
      - conditions: '{{ command == "button_3_double_press" }}'
        sequence: !input Button_3_2x_Press
      - conditions: '{{ command == "button_3_triple_press" }}'
        sequence: !input Button_3_3x_Press
      - conditions: '{{ command == "button_3_quadruple_press" }}'
        sequence: !input Button_3_4x_Press
      - conditions: '{{ command == "button_3_quintuple_press" }}'
        sequence: !input Button_3_5x_Press
      - conditions: '{{ command == "button_3_hold"}}'
        sequence: !input Button_3_Long_Press
      - conditions: '{{ command == "button_3_short_release" }}'
        sequence: !input Button_3_Long_Release
      - conditions: '{{ command == "button_3_long_release" }}'
        sequence: !input Button_3_Short_Release

      # Button 4
      - conditions: '{{ command == "button_4_press" }}'
        sequence: !input Button_4_1x_Press
      - conditions: '{{ command == "button_4_double_press" }}'
        sequence: !input Button_4_2x_Press
      - conditions: '{{ command == "button_4_triple_press" }}'
        sequence: !input Button_4_3x_Press
      - conditions: '{{ command == "button_4_quadruple_press" }}'
        sequence: !input Button_4_4x_Press
      - conditions: '{{ command == "button_4_quintuple_press" }}'
        sequence: !input Button_4_5x_Press
      - conditions: '{{ command == "button_4_hold"}}'
        sequence: !input Button_4_Long_Press
      - conditions: '{{ command == "button_4_short_release" }}'
        sequence: !input Button_4_Long_Release
      - conditions: '{{ command == "button_4_long_release" }}'
        sequence: !input Button_4_Short_Release

      # Rotary Dial
      - conditions: '{{ command == "step_with_on_off" and step_mode == "StepMode.Up"}}'
        sequence: !input Rotary_Clockwise
      - conditions: '{{ command == "step_with_on_off" and step_mode == "StepMode.Down"}}'
        sequence: !input Rotary_Counterclockwise
