blueprint:
  domain: automation
  name: Philips Hue Smart Remote v2 (RWL022)
  description: Philips Hue v2 Remotes (RWL022) configuration using ZHA

  input:
    zha_device:
      name: Philips Hue Remote v2
      description: List of available Philips Hue v2 Remotes
      selector:
        device:
          integration: zha
          model: RWL022
          multiple: false

    Power_Press:
      name: Power Button Press
      description: Power button has been pressed
      default: [ ]
      selector:
        action: { }
    Power_Press2x:
      name: Power Button Press 2x
      description: Power button has been pressed 2x times
      default: [ ]
      selector:
        action: { }
    Power_Press3x:
      name: Power Button Press 3x
      description: Power button has been pressed 3x times
      default: [ ]
      selector:
        action: { }
    Power_Press4x:
      name: Power Button Press 4x
      description: Power button has been pressed 4x times
      default: [ ]
      selector:
        action: { }
    Power_Press5x:
      name: Power Button Press 5x
      description: Power button has been pressed 5x times
      default: [ ]
      selector:
        action: { }
    Power_Release:
      name: Power Button Release
      description: Power button has been released
      default: [ ]
      selector:
        action: { }
    Power_HoldPress:
      name: Power Button Hold
      description: Power button has been held down
      default: [ ]
      selector:
        action: { }
    Power_HoldRelease:
      name: Power Button Hold Release
      description: Power button has been released after being held down
      default: [ ]
      selector:
        action: { }

    IncreaseBrightness_Press:
      name: Increase Brightness Press
      description: Decrease Brightness has been pressed
      default: [ ]
      selector:
        action: { }
    IncreaseBrightness_Press2x:
      name: Increase Brightness Press 2x
      description: Increase Brightness has been pressed 2x times
      default: [ ]
      selector:
        action: { }
    IncreaseBrightness_Press3x:
      name: Increase Brightness Press 3x
      description: Increase Brightness has been pressed 3x times
      default: [ ]
      selector:
        action: { }
    IncreaseBrightness_Press4x:
      name: Increase Brightness Press 4x
      description: Increase Brightness has been pressed 4x times
      default: [ ]
      selector:
        action: { }
    IncreaseBrightness_Press5x:
      name: Decrease Brightness Press 5x
      description: Increase Brightness has been pressed 5x times
      default: [ ]
      selector:
        action: { }
    IncreaseBrightness_Release:
      name: Increase Brightness Release
      description: Increase Brightness has been released
      default: [ ]
      selector:
        action: { }
    IncreaseBrightness_HoldPress:
      name: Increase Brightness Hold
      description: Increase Brightness held down
      default: [ ]
      selector:
        action: { }
    IncreaseBrightness_HoldRelease:
      name: Increase Brightness Hold Release
      description: Increase Brightness released after being held down
      default: [ ]
      selector:
        action: { }

    DecreaseBrightness_Press:
      name: Decrease Brightness Press
      description: Decrease Brightness pressed
      default: [ ]
      selector:
        action: { }
    DecreaseBrightness_Press2x:
      name: Decrease Brightness 2x
      description: Decrease Brightness has been pressed 2x times
      default: [ ]
      selector:
        action: { }
    DecreaseBrightness_Press3x:
      name: Decrease Brightness 3x
      description: Decrease Brightness has been pressed 3x times
      default: [ ]
      selector:
        action: { }
    DecreaseBrightness_Press4x:
      name: Decrease Brightness Press 4x
      description: Decrease Brightness has been pressed 4x times
      default: [ ]
      selector:
        action: { }
    DecreaseBrightness_Press5x:
      name: Decrease Brightness Press 5x
      description: Decrease Brightness has been pressed 5x times
      default: [ ]
      selector:
        action: { }
    DecreaseBrightness_Release:
      name: Decrease Brightness Release
      description: Decrease Brightness has been released
      default: [ ]
      selector:
        action: { }
    DecreaseBrightness_HoldPress:
      name: Decrease Brightness Hold
      description: Decrease Brightness has been held down
      default: [ ]
      selector:
        action: { }
    DecreaseBrightness_HoldRelease:
      name: Decrease Brightness Hold Release
      description: Decrease Brightness has been released after being held down
      default: [ ]
      selector:
        action: { }

    Hue_Press:
      name: Hue Press
      description: Hue button has been pressed
      default: [ ]
      selector:
        action: { }
    Hue_Press2x:
      name: Hue Press 2x
      description: Hue button has been pressed 2x times
      default: [ ]
      selector:
        action: { }
    Hue_Press3x:
      name: Hue Press 3x
      description: Hue button has been pressed 3x times
      default: [ ]
      selector:
        action: { }
    Hue_Press4x:
      name: Hue Press 4x
      description: Hue button has been pressed 4x times
      default: [ ]
      selector:
        action: { }
    Hue_Press5x:
      name: Hue Press 5x
      description: Hue button has been pressed 5x times
      default: [ ]
      selector:
        action: { }
    Hue_Release:
      name: Hue Release
      description: Hue button has been released
      default: [ ]
      selector:
        action: { }
    Hue_HoldPress:
      name: Hue Hold
      description: Hue button has been being held down
      default: [ ]
      selector:
        action: { }
    Hue_HoldRelease:
      name: Hue Hold Release
      description: Hue button has been released after being held down
      default: [ ]
      selector:
        action: { }

mode: single
max_exceeded: silent
variables:
  device_id: !input zha_device

trigger:
  - platform: event
    event_type: zha_event
condition: "{{ trigger.event.data.device_id == device_id }}"

action:
  - variables:
      button: "{{ trigger.event.data.args.button }}"
      press_type: "{{ trigger.event.data.args.press_type }}"
      command_type: "{{ trigger.event.data.command }}"
  - service: logbook.log
    data:
      name: Button
      message: "{{ button }}"
  - service: logbook.log
    data:
      name: Press Type
      message: "{{ press_type }}"
  - service: logbook.log
    data:
      name: Device
      message: "{{ zha_device }}"
  - service: logbook.log
    data:
      name: Command
      message: "{{ command_type }}"
  - choose:
      - conditions: '{{ command_type == "on_press" }}'
        sequence: !input Power_Press
      - conditions: '{{ command_type == "on_double_press" }}'
        sequence: !input Power_Press2x
      - conditions: '{{ command_type == "on_triple_press" }}'
        sequence: !input Power_Press3x
      - conditions: '{{ command_type == "on_quadruple_press" }}'
        sequence: !input Power_Press4x
      - conditions: '{{ command_type == "on_quintuple_press" }}'
        sequence: !input Power_Press5x
      - conditions: '{{ command_type == "on_short_release" }}'
        sequence: !input Power_Release
      - conditions: '{{ command_type == "on_hold" }}'
        sequence: !input Power_HoldPress
      - conditions: '{{ command_type == "on_long_release" }}'
        sequence: !input Power_HoldRelease
      - conditions: '{{ command_type == "up_press" }}'
        sequence: !input IncreaseBrightness_Press
      - conditions: '{{ command_type == "up_double_press" }}'
        sequence: !input IncreaseBrightness_Press2x
      - conditions: '{{ command_type == "up_triple_press" }}'
        sequence: !input IncreaseBrightness_Press3x
      - conditions: '{{ command_type == "up_quadruple_press" }}'
        sequence: !input IncreaseBrightness_Press4x
      - conditions: '{{ command_type == "up_quintuple_press" }}'
        sequence: !input IncreaseBrightness_Press5x
      - conditions: '{{ command_type == "up_short_release" }}'
        sequence: !input IncreaseBrightness_Release
      - conditions: '{{ command_type == "up_hold" }}'
        sequence: !input IncreaseBrightness_HoldPress
      - conditions: '{{ command_type == "up_long_release" }}'
        sequence: !input IncreaseBrightness_HoldRelease
      - conditions: '{{ command_type == "down_press" }}'
        sequence: !input DecreaseBrightness_Press
      - conditions: '{{ command_type == "down_double_press" }}'
        sequence: !input DecreaseBrightness_Press2x
      - conditions: '{{ command_type == "down_triple_press" }}'
        sequence: !input DecreaseBrightness_Press3x
      - conditions: '{{ command_type == "down_quadruple_press" }}'
        sequence: !input DecreaseBrightness_Press4x
      - conditions: '{{ command_type == "down_quintuple_press" }}'
        sequence: !input DecreaseBrightness_Press5x
      - conditions: '{{ command_type == "down_short_release" }}'
        sequence: !input DecreaseBrightness_Release
      - conditions: '{{ command_type == "down_hold" }}'
        sequence: !input DecreaseBrightness_HoldPress
      - conditions: '{{ command_type == "down_long_release" }}'
        sequence: !input DecreaseBrightness_HoldRelease
      - conditions: '{{ command_type == "off_press" }}'
        sequence: !input Hue_Press
      - conditions: '{{ command_type == "off_double_press" }}'
        sequence: !input Hue_Press2x
      - conditions: '{{ command_type == "off_triple_press" }}'
        sequence: !input Hue_Press3x
      - conditions: '{{ command_type == "off_quadruple_press" }}'
        sequence: !input Hue_Press4x
      - conditions: '{{ command_type == "off_quintuple_press" }}'
        sequence: !input Hue_Press5x
      - conditions: '{{ command_type == "off_short_release" }}'
        sequence: !input Hue_Release
      - conditions: '{{ command_type == "off_hold" }}'
        sequence: !input Hue_HoldPress
      - conditions: '{{ command_type == "off_long_release" }}'
        sequence: !input Hue_HoldRelease
